-- Phase 6: Alert Detection Engine — persistent alert storage

CREATE TABLE IF NOT EXISTS telemetry_alerts (
    id               VARCHAR(36)     PRIMARY KEY,
    device_id        VARCHAR(255)    NOT NULL,
    snapshot_id      VARCHAR(36)     REFERENCES telemetry_snapshots(id) ON DELETE SET NULL,
    category         VARCHAR(30)     NOT NULL,   -- Overheating | Battery | Disk | Network
    severity         VARCHAR(10)     NOT NULL,   -- Info | Warning | Critical
    rule_id          VARCHAR(60)     NOT NULL,
    message          TEXT            NOT NULL,
    metric_name      VARCHAR(60)     NOT NULL,
    metric_value     REAL            NOT NULL,
    threshold_value  REAL            NOT NULL,
    triggered_at     TIMESTAMP       NOT NULL DEFAULT NOW(),
    acknowledged     BOOLEAN         NOT NULL DEFAULT FALSE,
    acknowledged_at  TIMESTAMP
);

-- Fast lookup: unacknowledged alerts per device (most common query)
CREATE INDEX IF NOT EXISTS idx_alerts_device_unack
    ON telemetry_alerts (device_id, acknowledged, triggered_at DESC);

-- Fast lookup: alerts by severity (dashboard alert feed)
CREATE INDEX IF NOT EXISTS idx_alerts_severity
    ON telemetry_alerts (severity, triggered_at DESC);

-- Fast lookup: alerts by category
CREATE INDEX IF NOT EXISTS idx_alerts_category
    ON telemetry_alerts (category, triggered_at DESC);

-- Fast lookup: alerts by snapshot (for joining with telemetry)
CREATE INDEX IF NOT EXISTS idx_alerts_snapshot
    ON telemetry_alerts (snapshot_id);

COMMENT ON TABLE telemetry_alerts IS 'Rule-based alerts generated by Phase 6 Alert Detection Engine';
